# Generated by Django 5.0 on 2023-12-28 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='countInStock',
        ),
        migrations.AddField(
            model_name='product',
            name='inci',
            field=models.TextField(blank=True, null=True),
        ),
    ]
