# Generated by Django 5.0 on 2023-12-30 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ean',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
