# Generated by Django 5.0 on 2024-01-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_product_ean_alter_product_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='crueltyFree',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='vegan',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
